name: Tools
version: ${pluginVersion}
main: gamesmc.tools.Tools
api-version: 1.18
author: ReferTV
description: "Tools plugin"

commands:
  tools:
  online:
  gamemode:
    usage: /gamemode <1/2/3>
  fly:
  crafting:
  anvil:
  loom:
  grindstone:
  stonecutter:
  cartographytable:
  smitchingtable:
